### ISSUE TITLE
Write a vagrant configuration file for common environment

### ISSUE THREAD

**Issue by senongtor** [DevOps-Shopcarts-S17/devops-shopcarts-s17#1]
**As a** developer 
**I need** a vagrant configuration  
**So that** every developer can be provided with a same virtual machine environment that can be used for testing the running of the restful service via simple `vagrant up` and `vagrant ssh` command.

**Assumptions:** 
* The virtual machine will be running ubuntu trusty
* The port that gets forwarded is 8888
* The ubuntu will have all the tools needed to run python flask apps (restful services)
* There will be a shared folder so that you can code on the host machine directly.

**Acceptance Criteria:**
```
Given this vagrant file
When I do vagrant up
Then I will be able to bootstrap a ubuntu virtual machine with everything a developer needs to configure and run a restful service.
```

**Comment by WesPainter** [comment]
Currently the port forwarded is at 5000, but the issue assumption states it will be 8888.

**Comment by senongtor** [comment]
@WesPainter nice catch
