### ISSUE TITLE
Add .travis.yml configuration file

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#106]
**As a** developer  
**I need** a travis.yml configuration file
**So that** when I submit a pull request or push to master, test cases are run

**Assumptions:** 
* TravisCI will monitor github for push and pull requests
* 

**Acceptance Criteria:**
```
Given a .travis.yml configuration file
When a push to master or pull request is executed
Then travis CI will run tests cases
```

**Comment by Pratik-Karnik** [comment]
Completed and merged
