### ISSUE TITLE
Document index method in shopcart.py

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#113]
**As a** client
**I need** documentation on the index method
**So that** I can read and understand the API endpoint

**Assumptions:** 
* Documentation using swagger Flasgger
* Documentation will be done present beneath the method signature

**Acceptance Criteria:**
```
Given a running instance of the server
When I navigate to the swagger documentation page
Then the documentation for GET / which routes to the index method will be present
```

**Comment by Pratik-Karnik** [comment]
@WesPainter @jiweix @ceciliazhang12 Is this needed? Prof's repo does not have swagger doc for index

**Comment by Pratik-Karnik** [comment]
Not needed
