### ISSUE TITLE
Document put_product method in server.py

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#120]
**As a** client
**I need** documentation on the put_product method
**So that** I can read and understand the API endpoint

**Assumptions:** 
* Documentation using swagger Flasgger
* Documentation will be done present beneath the method signature

**Acceptance Criteria:**
```
Given a running instance of the server
When I navigate to the swagger documentation page
Then the documentation for PUT /shopcarts/<sid>/products/<sku> which routes to the put_product method will be present
```

**Comment by Pratik-Karnik** [comment]
Closed by PR #182
