### ISSUE TITLE
Document subtotal_shopcart method in server.py

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#123]
**As a** client
**I need** documentation on the subtotal_shopcart method
**So that** I can read and understand the API endpoint

**Assumptions:** 
* Documentation using swagger Flasgger
* Documentation will be done present beneath the method signature

**Acceptance Criteria:**
```
Given a running instance of the server
When I navigate to the swagger documentation page
Then the documentation for PUT /shopcarts/<sid>/subtotal which routes to the subtotal_shopcart method will be present
```

**Comment by Pratik-Karnik** [comment]
Closed by PR #182
