### ISSUE TITLE
Push docker image to the Bluemix Docker Registry using the cf ic

### ISSUE THREAD

**Issue by jiweix** [DevOps-Shopcarts-S17/devops-shopcarts-s17#166]
**As a** developer
**I need** my docker image run on Bluemix 
**So that** everyone can use my service

**Assumptions:** 
* Docker image is ready
* namespace will be nyu_shopcarts

**Acceptance Criteria:**
```
Given the docker image in local machine, and Cloud Foundry command line interface installed
When I tag the image and push it to Bluemix
Then I can access this service from Bluemix 
```

**Comment by jiweix** [comment]
Please add the docker url to readme if anyone finish this issue

**Comment by WesPainter** [comment]
Docker image in bluemix as nyu_shopcarts/nyu-shopcarts-service.
