### ISSUE TITLE
Create a Container Group and Redis Service on Bluemix 

### ISSUE THREAD

**Issue by jiweix** [DevOps-Shopcarts-S17/devops-shopcarts-s17#167]
**As a** developer
**I need** least 2 instances of my containers running and Redis service running
**So that** customer can use this service 

**Assumptions:** 
* the docker image is pushed to bluemix already

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by WesPainter** [comment]
Container group created with url https://container-nyu-shopcarts-service.mybluemix.net
