### ISSUE TITLE
Create a new DevOps Pipeline to automatically build and deploy containers to Bluemix

### ISSUE THREAD

**Issue by jiweix** [DevOps-Shopcarts-S17/devops-shopcarts-s17#168]
**As a** developer
**I need** a DevOps pipeline
**So that** I can automatically deploy containers

**Assumptions:** 
* merging a pull request with master triggers pipeline
* container environment at container-nyu-shopcarts-service.mybluemix.net

**Acceptance Criteria:**
```
Given an update to application code
When the change is merged with master
Then the application will build the containers and deploy them to a container group of 2 instances
```

**Comment by WesPainter** [comment]
Pull #186 to test pipeline was successful.

**Comment by WesPainter** [comment]
Removed testing requirements per update from instructor.

**Comment by WesPainter** [comment]
@jiweix @ceciliazhang12 @Pratik-Karnik Pratik has credentials to access bluemix. pipelines are all set up so if you would like to take a look ask me or Pratik and we'll will give you the credentials until we can figure out how to invite members to the organization.  There are three spaces related to the project: dev, prod, and container.  dev holds the dev application as well as the dev redis instance.  prod holds prod items, and containers has the container group and supporting redis application.  There are two toolchains automating the pipeline of the container group and the normal CF deployment.  If you have any questions about the setup of something please ask before making changes... bluemix is sensitive. :)

**Comment by Pratik-Karnik** [comment]
Completed
