### ISSUE TITLE
Create DELETE API for deleting a shopping cart

### ISSUE THREAD

**Issue by Pratik-Karnik** [DevOps-Shopcarts-S17/devops-shopcarts-s17#18]
**As a** ...  user
**I need** ...  to be able to delete a shopping cart
**So that** ...  I delete the complete shopping cart

**Acceptance Criteria:**
```
Given ... this API
When ... I type /shopcarts/{id}
Then ... I should be able to delete a particular shopping cart
```

**Comment by WesPainter** [comment]
This implementation doesn't work.  Look at the following line:

` del shopping_carts[sid]`

This indexes into shopping carts directly using sid.  However, you'll have to iterate through the shopping carts and look for an sid match.  Your sid doesn't necessarily reflect the position of that sopping cart in the shopping_carts list data store.  You should iterate through sopping carts, look for a match to sid, then delete.

**Comment by WesPainter** [comment]
To see the issue with this implementation, you can issue a DELETE /shopcarts/2, and then follow it with a DELETE /shopcarts/3.  This will fail even though the shopping cart with sid 3 exists, because it is now in the second position in the shopping_carts list.
