### ISSUE TITLE
Create a sample data schema

### ISSUE THREAD

**Issue by Pratik-Karnik** [DevOps-Shopcarts-S17/devops-shopcarts-s17#4]
Create a sample data schema for a few records.

Data Schema may include attributes like product name, quantity, cost, description etc.

**Comment by WesPainter** [comment]
Not sure this is done.  There should be a unique id for each shopping cart.  We shouldn't bank on the user id as an identifier.  This will also allow multiple carts per user.

**Comment by Pratik-Karnik** [comment]
@WesPainter Gotcha

**Comment by Pratik-Karnik** [comment]
We should have an auto-generated shopping cart ID when we create a new shopping cart so that should be added to the sample data schema.
