### ISSUE TITLE
Bug fix PUT operation for products in a shopping cart

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#45]
**As a** USER
**I need** to be able to issue a put request for products in a shopping cart without error
**So that** I can change products in my shopping cart

**Assumptions:** 
* Current implementation is faulty, returns error 500

**Acceptance Criteria:**
```
Given a shopping cart with products in it
When I issue PUT /shopcarts/sid/products/sku with a properly formatted payload
Then the product should update with a HTTP 200 response code
```

**Comment by senongtor** [comment]
@WesPainter Shouldn't update success return HTTP 200 not 201?

**Comment by WesPainter** [comment]
You're right, fixed
