### ISSUE TITLE
Research about ShopCarts

### ISSUE THREAD

**Issue by Pratik-Karnik** [DevOps-Shopcarts-S17/devops-shopcarts-s17#5]
**As a** developer
**I need** to know more about professional and sophisticated shopping carts API
**So that** I can make a better application

Some examples:

- Amazon APIs

- api2cart

**Comment by api2cart** [comment]
Hello, 
If you want to know more about API2Cart API, we would be glad to answer any questions regarding it.
Thanks

**Comment by Pratik-Karnik** [comment]
Not needed at the moment.
