### ISSUE TITLE
Create TDD file

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#58]
**As a** Developer
**I need** A file for holding unit tests
**So that** I can write unit tests to automatically verify software

**Assumptions:** 
* the file will be called test_shopcart.py

**Acceptance Criteria:**
```
Given the unit test file test_shopcart.py
When I use the file with python -m unittest
Then unit tests will be run against server.py
```

**Comment by Pratik-Karnik** [comment]
Completed
