### ISSUE TITLE
Write test cases for get_shopcart method

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#61]
**As a** developer
**I need** test cases for the get_shopcart method of shopcart.py
**So that** When I make changes, I can run tests to verify integrity of get_shopcart method

**Assumptions:** 
* Test cases will be written in PyUnit syntax
* Test cases will reside in test_shopcart.py

**Acceptance Criteria:**
```
Given test cases written in test_shopcart.py
When I run python coverage with the test cases
Then at least 95% of the get_shopcart method should be covered in the test
```

**Comment by Pratik-Karnik** [comment]
Completed and merged.
