### ISSUE TITLE
Write test cases for get_products method

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#62]
**As a** developer
**I need** test cases for the get_products method of shopcart.py
**So that** When I make changes, I can run tests to verify integrity of get_products method

**Assumptions:** 
* Test cases will be written in PyUnit syntax
* Test cases will reside in test_shopcart.py

**Acceptance Criteria:**
```
Given test cases written in test_shopcart.py
When I run python coverage with the test cases
Then at least 95% of the get_products method should be covered in the test
```

**Comment by Pratik-Karnik** [comment]
Is this a duplicate of #95? @WesPainter @ceciliazhang12 @jiweix

**Comment by WesPainter** [comment]
You are right, I misread the open issue as get_product and didn't see get_products in completed.

**Comment by Pratik-Karnik** [comment]
So I think this is a duplicate then.

**Comment by WesPainter** [comment]
@ceciliazhang12 I hope you didn't get too far on this.

**Comment by ceciliazhang12** [comment]
It's ok, I just began. So maybe we should close this one instead?

**Comment by Pratik-Karnik** [comment]
@ceciliazhang12 Yes lets do that!!

**Comment by Pratik-Karnik** [comment]
Closing as duplicated by #95
