### ISSUE TITLE
Create simple shopcarts hello world server in Flask

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#9]
**As a** Developer
**I need** a flask application file
**So that** I can add features to the shopcart

**Assumptions:** 
* the name of the server file will be shopcart.py

**Acceptance Criteria:**
```
Given an flask server application shopcart.py
When I do flask run in the virtual machine
Then a simple hello world flask shopcarts server will run on port 8888
```

**Comment by senongtor** [comment]
@WesPainter Do you really want just a minimal server that will echo hello world or do you want a server that basically uses code pet flask server? We can really just copy the example code and make some minor changes

**Comment by WesPainter** [comment]
@senongtor 

I just figured we could start with a minimal server, and after we meet to plan out our tasks, we can copy paste the code into the server that we needed for that specific task.  Just-in-time copy/paste so we don't do anything unnecessary before we have the tasks and end up doing something useless.

**Comment by senongtor** [comment]
@WesPainter Got it
