### ISSUE TITLE
Write test cases for Query

### ISSUE THREAD

**Issue by Pratik-Karnik** [DevOps-Shopcarts-S17/devops-shopcarts-s17#90]
**As a** developer
**I need** test cases for the proper execution of queries in shopcart.py
**So that** When I make changes, I can run tests to verify the integrity of the result of the queries

**Assumptions:** 
* Test cases will be written in PyUnit syntax
* Test cases will reside in test_shopcart.py

**Acceptance Criteria:**
```
Given test cases written in test_shopcart.py
When I run python coverage with the test cases
Then at least 95% of the put_product method should be covered in the test
```

**Comment by WesPainter** [comment]
@Pratik-Karnik What tests are you looking for specifically? Execution of queries like adding or removing things from the shopping cart?

**Comment by Pratik-Karnik** [comment]
@WesPainter I meant to say queries like /shopcarts/?sid=1 /shopcarts/1/?name="". Something on these lines...

**Comment by WesPainter** [comment]
@Pratik-Karnik Aren't these covered with other issues? For instance, writing test cases for list_shopcarts should include testing possible queries on listing shopcarts? /shopcarts?uid=2.  Although reviewing some changes this doesn't seem to have happened, so I can add them in

**Comment by Pratik-Karnik** [comment]
@wes I dont think these cases were handled before
