### ISSUE TITLE
Create tests for get_products method in shopcart

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#95]
**As a** developer
**I need** test cases for the proper execution of get_products in shopcart.py
**So that** When I make changes, I can run tests to verify the integrity of the result of the get_products

**Assumptions:** 
* Test cases will be written in PyUnit syntax
* Test cases will reside in test_shopcart.py

**Acceptance Criteria:**
```
Given test cases written in test_shopcart.py
When I run python coverage with the test cases
Then at least 95% of the get_products method should be covered in the test
```

**Comment by Pratik-Karnik** [comment]
Completed and merged.
